FROM node:20.10.0-alpine AS build

WORKDIR /build
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
RUN yarn sequelize db:migrate

FROM node:20.10.0-alpine

WORKDIR /api
RUN chmod -R 777 /api
USER node
COPY package.json yarn.lock .env .env.* .sequelizerc ./
RUN yarn install --production --frozen-lockfile
COPY --from=build /build/dist ./build/db.sqlite ./

CMD ["node", "main.js"]